services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    profiles:
      - db
      - full

  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - WS_HOST=0.0.0.0
      - WS_PORT=8000
    profiles:
      - full
